# Generated by Django 5.0.14 on 2026-06-25 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('tracking_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public tracking token for anonymous complaint status checks. Separate from the PK to avoid leaking internal identifiers.', unique=True)),
                ('is_anonymous', models.BooleanField(db_index=True, default=True, help_text='Whether this complaint was filed anonymously.')),
                ('subject', models.CharField(help_text='Brief subject line of the complaint.', max_length=300)),
                ('body', models.TextField(help_text='Full complaint body (supports rich text / HTML).')),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated to Chairman'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='UNREAD', help_text='Current status of the complaint.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', help_text='Priority level assigned to the complaint.', max_length=10)),
                ('nid_verification_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of NID verification. Only relevant for non-anonymous complaints that include an NID photo.', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes added by UP members (not visible to citizen).')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the complaint status was changed to RESOLVED.', null=True)),
                ('complainant', models.ForeignKey(blank=True, help_text='The verified user who filed this complaint. NULL for anonymous complaints.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('file_url', models.URLField(help_text='S3 object URL of the uploaded file.', max_length=1024)),
                ('object_key', models.CharField(help_text='S3 object key for generating presigned download URLs.', max_length=512)),
                ('file_name', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('file_type', models.CharField(help_text="MIME type of the file (e.g., 'image/jpeg', 'application/pdf').", max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('complaint', models.ForeignKey(help_text='The complaint this attachment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Attachment',
                'verbose_name_plural': 'Complaint Attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('old_status', models.CharField(choices=[('UNREAD', 'Unread'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated to Chairman'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], help_text='The previous status before the change.', max_length=20)),
                ('new_status', models.CharField(choices=[('UNREAD', 'Unread'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated to Chairman'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], help_text='The new status after the change.', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes explaining the reason for the status change.')),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who made this status change. NULL for system-initiated changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(help_text='The complaint this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Status Log Entry',
                'verbose_name_plural': 'Status Log Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NIDVerificationTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', help_text='Celery task ID for tracking the async job.', max_length=255)),
                ('nid_image_url', models.URLField(help_text='S3 URL of the NID card photo to process.', max_length=1024)),
                ('nid_image_object_key', models.CharField(blank=True, default='', help_text='S3 object key for downloading the NID image.', max_length=512)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current status of the NID verification pipeline.', max_length=20)),
                ('extracted_name', models.CharField(blank=True, default='', help_text='Name extracted from the NID card via OCR.', max_length=255)),
                ('extracted_address', models.TextField(blank=True, default='', help_text='Address extracted from the NID card via OCR.')),
                ('extracted_nid_number', models.CharField(blank=True, default='', help_text='NID number extracted from the card via OCR.', max_length=20)),
                ('jurisdiction_match', models.BooleanField(blank=True, help_text="Whether the extracted address falls within the Union Parishad's jurisdiction. NULL = not yet checked.", null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the verification pipeline failed.')),
                ('complaint', models.OneToOneField(help_text='The complaint that triggered this NID verification.', on_delete=django.db.models.deletion.CASCADE, related_name='nid_task', to='complaints.complaint')),
                ('created_user', models.ForeignKey(blank=True, help_text='The user account auto-created after successful NID verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nid_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NID Verification Task',
                'verbose_name_plural': 'NID Verification Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnionParishad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. True means logically deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official name of the Union Parishad.', max_length=255)),
                ('district', models.CharField(db_index=True, help_text='District name (জেলা) for jurisdiction matching.', max_length=100)),
                ('upazila', models.CharField(db_index=True, help_text='Upazila/Thana name (উপজেলা) for jurisdiction matching.', max_length=100)),
                ('union_name', models.CharField(help_text='Union name (ইউনিয়ন).', max_length=100)),
                ('chairman_name', models.CharField(blank=True, default='', help_text='Name of the current UP Chairman.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', help_text='Official contact phone number.', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Official contact email address.', max_length=254)),
                ('address', models.TextField(blank=True, default='', help_text='Full physical address of the UP office.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the UP is currently operational.')),
            ],
            options={
                'verbose_name': 'Union Parishad',
                'verbose_name_plural': 'Union Parishads',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['district', 'upazila'], name='idx_up_district_upazila')],
            },
        ),
        migrations.AddConstraint(
            model_name='unionparishad',
            constraint=models.UniqueConstraint(fields=('district', 'upazila', 'union_name'), name='uq_up_district_upazila_union'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='union_parishad',
            field=models.ForeignKey(help_text='The Union Parishad this complaint is filed against.', on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.unionparishad'),
        ),
        migrations.AddIndex(
            model_name='complaintstatuslog',
            index=models.Index(fields=['complaint', 'created_at'], name='idx_statuslog_complaint_date'),
        ),
        migrations.AddIndex(
            model_name='nidverificationtask',
            index=models.Index(fields=['status', 'created_at'], name='idx_nidtask_status_date'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='idx_complaint_status_date'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['union_parishad', 'status'], name='idx_complaint_up_status'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complainant', 'status'], name='idx_complaint_user_status'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['is_anonymous', 'status'], name='idx_complaint_anon_status'),
        ),
    ]
