# Generated by Django 5.0.14 on 2026-06-25 09:34

import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier for the user.', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Unique email address — used for login and notifications.', max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Contact phone number (e.g., +8801XXXXXXXXX).', max_length=20)),
                ('nid_number', models.CharField(blank=True, db_index=True, help_text='Bangladesh National ID number (10 or 17 digits).', max_length=20, null=True, unique=True)),
                ('nid_name', models.CharField(blank=True, default='', help_text='Full name as printed on the NID card.', max_length=255)),
                ('nid_address', models.TextField(blank=True, default='', help_text='Address as printed on the NID card.')),
                ('nid_verified', models.BooleanField(db_index=True, default=False, help_text='Whether NID verification has been completed successfully.')),
                ('nid_image_url', models.URLField(blank=True, default='', help_text='S3 URL of the uploaded NID card photo.')),
                ('auto_generated_password', models.CharField(blank=True, default='', help_text="Plaintext auto-generated password for NID-verified users. Cleared after the user's first login or after 24 hours.", max_length=128)),
                ('is_up_member', models.BooleanField(db_index=True, default=False, help_text='Whether this user is a Union Parishad member/admin.')),
                ('is_chairman', models.BooleanField(db_index=True, default=False, help_text='Whether this user is the Union Parishad Chairman.')),
                ('avatar_url', models.URLField(blank=True, default='', help_text="URL to the user's profile picture.")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['nid_number'], name='idx_user_nid'), models.Index(fields=['is_up_member', 'is_active'], name='idx_user_up_member'), models.Index(fields=['is_chairman', 'is_active'], name='idx_user_chairman')],
            },
        ),
    ]
